#!/bin/bash
FILE=$1                                                                 
MCU="$(head -2 $1 | tail -1)"
FILE=${FILE%%.*}
avr-gcc -mmcu=$MCU $1 -o $FILE.o
avr-objcopy -j .text -j .data -O ihex $FILE.o $FILE.hex
sudo dfu-programmer $MCU erase
sudo dfu-programmer $MCU flash $FILE.hex
sudo dfu-programmer $MCU reset
rm $FILE.o
rm $FILE.hex
echo done
